export const IS_LOADING = 'IS_LOADING'
export const GET_GUESTS = 'GET_GUESTS'
export const CREATE_GUEST = 'CREATE_GUEST'
export const UPDATE_GUEST = 'UPDATE_GUEST'
export const DELETE_GUEST = 'DELETE_GUEST'
